name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} --password-stdin
      - run: docker build -t gving/docker-nuxt-test -f Dockerfile.dev .
      - run: docker run -e CI=true gving/docker-nuxt-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip ./dist -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-nuxt
          environment_name: Dockernuxt-env
          existing_bucket_name: elasticbeanstalk-us-west-2-787458233150
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip